apiVersion: v1
kind: Service
metadata:
  name: xenon-opentracing-demo
  labels:
    app: xenon-opentracing-demo
spec:
  ports:
  - name: xenon
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: xenon-opentracing-demo
  type: LoadBalancer
