version: '2'
services:
  control:
    container_name: jepsen-control
    hostname: control
    build: ./control
    volumes:
     - /Users/tliaqat/jepsen-xenon:/jepsen-xenon
    env_file: ./secret/control.env
    privileged: true
    links:
      - n1
      - n2
      - n3
      - n4
      - n5
  node:
    container_name: jepsen-node
    build: ./node
    env_file: ./secret/node.env
    privileged: true
  n1:
    extends: node
    container_name: jepsen-n1
    hostname: n1
  n2:
    extends: node
    container_name: jepsen-n2
    hostname: n2
  n3:
    extends: node
    container_name: jepsen-n3
    hostname: n3
  n4:
    extends: node
    container_name: jepsen-n4
    hostname: n4
  n5:
    extends: node
    container_name: jepsen-n5
    hostname: n5
